# Project 1

This describes the first bigger programming project in the course, devoted to artificial
neural networks.
Application: Recognizing handwritten numbers
Most people effortlessly recognise these digits as 504192. This ease is deceptive. The
difficulty of visual pattern recognition becomes obvious when trying to write a computer
program to recognise digits like the above. What seems easy when we do it ourselves
suddenly becomes extremely difficult. Simple notions about how we recognise shapes -
“a 9 has a loop at the top and a vertical line at the bottom right” - turn out to be not
so easy to express algorithmically. If you try to specify such rules, you quickly get lost
in a quagmire of exceptions, restrictions and special cases. It seems hopeless.
Neural networks approach the problem differently. The idea is to use a large number of
handwritten digits, called training examples, and then develop a system that can learn
from these training examples. In other words, the neural network uses the examples to
automatically derive rules for recognising handwritten digits. In addition, by increasing
the number of training examples, the network can learn more about handwriting and
thus improve its accuracy.

In [1]:
# Imports
import numpy as np
# pickle is for loading the dataset
import pickle

### Task 1

Implement a feedforward neural network (as a class) consisting of 3 layers (input,
hidden, output layer), where each layer can contain any number of neurons. Use
the sigmoid function as the activation function.

### Task 3

Implement the stochastic gradient method (SGD) to train the network. The implementation of the SGD should allow for different mini-batch sizes and different
numbers of epochs. An epoch is the complete pass of the training data through
the learning algorithm.

### Task 4
Implement the backpropagation algorithm (used in SGD to effectively calculate
the derivative).

In [17]:
# Feedforward NN Class
class FeedForwardNeuralNetwork():
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        # randn was used to achieve a better initial estimate of the weights and biases by having random values from a 
        # gaussian distribution. This results in better accuracy    
        self.weights_input_hidden = np.random.randn(self.input_size, self.hidden_size)
        self.bias_hidden = np.random.randn(self.hidden_size)
        self.weights_output_hidden = np.random.randn(self.hidden_size, self.output_size)
        self.bias_output = np.random.randn(self.output_size)

    def sigmoid(self, X):
        return 1 / (1 + np.exp(-X))
    
    # performs the forward pass through the neural network : that is, it does matrix multiplication(np.dot) and adds the
    # biases
    def forward(self, input_data):
        hidden_input = np.dot(input_data, self.weights_input_hidden) + self.bias_hidden
        hidden_output = self.sigmoid(hidden_input)
        output = np.dot(hidden_output, self.weights_output_hidden) + self.bias_output
        network_output = self.sigmoid(output)
        return network_output, hidden_output
    

    def train_sgd(self, X_train, Y_train, X_val, Y_val_onehot, learning_rate, batch_size, epochs):
        
        """
        X_train : training samples
        Y_train : training labels
        x_val   : validation samples
        Y_val_onehot  : validation labels
        learning_rate : step size for the backpropagation
        batch_size    : the number of samples processed before the model is updated
        epochs        : the number of complete passes through the entire dataset
        
        """
        # starting value for the loss
        best_val_loss = 100
        indices = np.arange(len(X_train))

        for epoch in range(epochs):
            # Shuffle the dataset so that the batch samples are not consecutive
            np.random.shuffle(indices)
            total_loss = []

            print(f'----------epoch: {epoch}------------')

            for i in range(0, len(X_train), batch_size):
                # Create mini-batches
                batch_indices = indices[i:i+batch_size]
                X_batch = X_train[batch_indices]
                y_batch = Y_train[batch_indices]

                # Forward pass
                network_output, hidden_output = self.forward(X_batch)

                # Backpropagation
                # Calculate loss and gradients
                # quadratic function (square loss) -- 1/2n is the mean from the formula
                loss = np.mean(0.5 * (network_output - y_batch) ** 2, axis=0)
                # the loss is averaged over the multiple losses to have a prettier print
                total_loss.append(np.mean(loss))  # Average over the mini-batch

                error = network_output - y_batch
                # calculate the gradient (derivative) of the loss with respect to the output of the neural network's final layer.
                d_output = error * network_output * (1 - network_output)
                # calculate the gradient of the loss with respect to the hidden layer's activations.
                d_hidden = np.dot(d_output, self.weights_output_hidden.T) * hidden_output * (1 - hidden_output)

                # Update weights and biases
                self.weights_output_hidden -= learning_rate * np.dot(hidden_output.T, d_output)
                self.bias_output -= learning_rate * np.sum(d_output, axis=0)
                self.weights_input_hidden -= learning_rate * np.dot(X_batch.T, d_hidden)
                self.bias_hidden -= learning_rate * np.sum(d_hidden, axis=0)
                
            print(f'mean total loss: {np.mean(total_loss)}')
                # Evaluate the model on the validation set
                #maybe comment it if we dont want the validation within the training
 ######################################               
#             val_loss, val_accuracy = self.evaluate(X_val, Y_val_onehot)
#             print(f"Epoch {epoch+1}: Validation Loss = {val_loss:.4f}, Validation Accuracy = {val_accuracy:.4f}")
    
#             # Check for early stopping or other criteria to save the best model
#             if val_loss < best_val_loss:
#                 best_val_loss = val_loss
#                 woh =  self.weights_output_hidden
#                 bo = self.bias_output
#                 wih = self.weights_input_hidden
#                 bh = self.bias_hidden

#         # Update weights to the best weights
#         self.weights_output_hidden = woh 
#         self.bias_output = bo
#         self.weights_input_hidden = wih
#         self.bias_hidden = bh
#############################

    def evaluate(self, X_val, Y_val):
        num_examples = len(X_val)
        # Forward pass on the validation data
        val_predictions = self.predict(X_val)
        # Calculate the mean loss
        val_loss = np.mean(0.5 * (val_predictions - X_val) ** 2, axis=0)

        # Convert predicted probabilities to predicted class labels (0-9)
        val_predictions_class = np.argmax(val_predictions, axis=1)
        
        # Convert true labels (one-hot encoded) to true class labels (0-9)
        Y_val_class = np.argmax(Y_val, axis=1)

        # Calculate accuracy
        val_accuracy = np.sum(val_predictions_class == Y_val_class) / num_examples

        return val_loss, val_accuracy

        
    def predict(self, input_data):
        # Perform a forward pass to generate predictions
        hidden_input = np.dot(input_data, self.weights_input_hidden) + self.bias_hidden
        hidden_output = self.sigmoid(hidden_input)
        output = np.dot(hidden_output, self.weights_output_hidden) + self.bias_output
        network_output = self.sigmoid(output)

        # Return the predicted values
        return network_output
    
    # functions to save the weights and biases in a txt file and to load it in the model
    def save_weights(self, filename):
        """
        This function saves the weights from the model in order i.e. the weights from the first layer and then second according
        to the labels given in the function call(which is before the equal)
        The file will have the .npz extension automatically if not written specifically in the filename
        """
        #probably want to save the number of neurons on each layer as well, and restore the model with load(but i thought about it a bit too late)
        np.savez(filename, weights_input_hidden=self.weights_input_hidden,
                           bias_hidden=self.bias_hidden,
                           weights_output_hidden= self.weights_output_hidden,
                           bias_output =self.bias_output)
    
    
    def load_weights(self,filename):
        """
        Loads the weights from a file. The filename should have the extension .npz in the name. The weights are loaded
        according to the labels which have been used to save it
        
        """
        all_weights = np.load(filename)
        self.weights_input_hidden = all_weights['weights_input_hidden']
        self.bias_hidden = all_weights['bias_hidden']
        self.weights_output_hidden = all_weights['weights_output_hidden']
        self.bias_output = all_weights['bias_output']


### Task 2

Reading in MNIST data (provided in canvas). The data is separated into training
data (50 000), validation data (10 000), and test data (10 000).

In [18]:
# Load MNIST data from mnist.pkl
with open('mnist.pkl/mnist.pkl', 'rb') as f:
    mnist_data = pickle.load(f, encoding='latin1')

# Extract training, validation, and test sets
train_data, valid_data, test_data = mnist_data

# Unpack the data into inputs and labels
X_train, Y_train = train_data
X_val, Y_val = valid_data
X_test, Y_test = test_data

# Convert inputs to numpy arrays
X_train = np.array(X_train)
X_val = np.array(X_val)
X_test = np.array(X_test)

# Convert labels to numpy arrays
Y_train = np.array(Y_train)
Y_val = np.array(Y_val)
Y_test = np.array(Y_test)


In [15]:
#f = open('test', "w")
np.savez('test', X_train=X_train,X_val=X_val,test=X_test)
X_val.shape


(10000, 784)

In [16]:
a = np.load('test.npz')
# if a[1][:].all() == X_test.all():
#     print("da")
# else:
#     print("nu")
a['test'].shape


(10000, 784)

### Normalize 

In [19]:

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_train_normalized = scaler.fit_transform(X_train)
X_val_normalized = scaler.transform(X_val)
X_test_normalized = scaler.transform(X_test)

### Onehot encode the labels

In [20]:
#one hot encoding - maps the numbers for all the dataset to vectors with 1s and 0s 
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse=False)
Y_train_onehot = encoder.fit_transform(Y_train.reshape(-1, 1))
Y_val_onehot = encoder.fit_transform(Y_val.reshape(-1, 1))

np.shape(Y_train_onehot), np.shape(X_train)

((50000, 10), (50000, 784))

### Task 5
Train and test the accuracy of the network for the following parameters:

• Input layer with 784 + 1 neurons

• hidden layer with 30 + 1 neurons

• Output layer with 10 neurons

As loss function use the quadratic function (square loss),
where (x, y) is a pair of training data, n the amount of used training data, and hw
represents the neural network.

In [21]:
nn = FeedForwardNeuralNetwork(784, 30, 10)

nn.train_sgd(X_train, Y_train_onehot, X_val, Y_val_onehot, 0.1, 1, 100)


----------epoch: 0------------
mean total loss: 0.022261697737608815
----------epoch: 1------------
mean total loss: 0.009607812493412336
----------epoch: 2------------
mean total loss: 0.007826324753374305
----------epoch: 3------------
mean total loss: 0.006956604445381115
----------epoch: 4------------
mean total loss: 0.006349415583317877
----------epoch: 5------------
mean total loss: 0.005914042392421485
----------epoch: 6------------
mean total loss: 0.005550460508692292
----------epoch: 7------------
mean total loss: 0.005251495453296409
----------epoch: 8------------
mean total loss: 0.00499551226065673
----------epoch: 9------------
mean total loss: 0.004786812226566876
----------epoch: 10------------
mean total loss: 0.004598412307938072
----------epoch: 11------------
mean total loss: 0.004423527087225509
----------epoch: 12------------
mean total loss: 0.004291259186388712
----------epoch: 13------------
mean total loss: 0.004155781945129261
----------epoch: 14------------

### Prediction

In [30]:
y_pred = nn.predict(X_test)
# Convert to labels (0-9)
y_pred = y_pred.argmax(axis=1)
print(y_pred)

[7 2 1 ... 4 5 6]


In [31]:
y_pred, Y_test

(array([7, 2, 1, ..., 4, 5, 6], dtype=int64),
 array([7, 2, 1, ..., 4, 5, 6], dtype=int64))

### Accuracy

In [32]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(Y_test, y_pred)
accuracy

0.9491

### Saving and loading the model


In [29]:
nn.save_weights('model_weights')
# not sure if this is the best or most elegant to do it -- probably want to integrate it somehow in the function
saved_nn = FeedForwardNeuralNetwork(784, 30, 10)
saved_nn.load_weights('model_weights.npz')
y_pred = nn.predict(X_test)
# Convert to labels (0-9)
y_pred = y_pred.argmax(axis=1)
print(y_pred)

[7 2 1 ... 4 5 6]


### Task 6
Print an output of the learning success per epoch.